project:
  type: website
  output-dir: docs

  render:
    - examples.qmd
    - index.qmd
    - explanations.qmd
    - tutorials.qmd
    - manuscript.qmd
    - reference.qmd
    - 1_Tutorials_DifferenceScores.qmd
    - 2_Tutorials_ResidualizedChangeScores.qmd
    - 3_Tutorials_LinearMixedModels.qmd
    - 1a_Examples_DifferenceScores_PairedTtests.qmd
    - 1b_Examples_DifferenceScores_SimpleRegression.qmd
    - 2_Examples_ResidualizedChangeScores.qmd
    - 3a_Examples_LinearMixedModels.qmd
    - 3b_Examples_LinearMixedModels.qmd
    - 4_Tutorials_SignedRankTest.qmd
    - 5_Tutorials_MarginalModels.qmd
    - 6_Tutorials_GeneralizedEstimatingEquations.qmd
    - 7_Tutorials_GeneralizedLinearMixedEffectsModels.qmd
    - 8_Tutorials_AutoregressiveCrosslaggedPanelModels.qmd
    - 9_Tutorials_LatentChangeScoresModels.qmd
    - 10_Tutorials_LatentGrowthCurveModels.qmd
    # - 11_Tutorials_MultivariateLatentGrowthCurveModels.qmd
    # - 12_Tutorials_LatentTransitionAnalysis.qmd
    # - 13_Tutorials_GrowthMixtureModels.qmd
    # - 14_Tutorials_StateTraitModels.qmd
    # - 15_Tutorials_RandomInterceptCrosslaggedPanelModels.qmd
    # - 16_Tutorials_LatentCurveModelsStructuredResiduals.qmd
    # - 1a_Examples_DifferenceScores_PairedTtests.qmd
    # - 4_Examples_SignedRankTest.qmd
    # - 5_Examples_MarginalModels.qmd
    # - 6_Examples_GeneralizedEstimatingEquations.qmd
    # - 7_Examples_GeneralizedLinearMixedEffectsModels.qmd
    # - 8_Examples_AutoregressiveCrosslaggedPanelModels.qmd
    # - 9_Examples_LatentChangeScoresModels.qmd
    # - 10_Examples_LatentGrowthCurveModels.qmd
    # - 11_Examples_MultivariateLatentGrowthCurveModels.qmd
    # - 12_Examples_LatentTransitionAnalysis.qmd
    # - 13_Examples_GrowthMixtureModels.qmd
    # - 14_Examples_StateTraitModels.qmd
    # - 15_Examples_RandomInterceptCrosslaggedPanelModels.qmd
    # - 16_Examples_LatentCurveModelsStructuredResiduals.qmd

website:
  title: "Longitudinal Analysis"
  favicon: "./figures/lights.png"
  twitter-card: true
  site-url: https://swhawes.github.io/abcd-biostats-longitudinal/
  page-navigation: true
  open-graph: true
  navbar:
    background: darkblue #slategray #primary #goldenrod
    search: true
    pinned: true
    collapsed: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Manuscript"
        file: manuscript.qmd
      - text: "Tutorials"
        file: tutorials.qmd
      - text: "ABCD Examples"
        file: examples.qmd
      - text: "Contribute"
        file: contribute.qmd
      - text: "Resources"
        file: resources.qmd
      #- text: "Documentation"
      #  file: documentation.qmd
    tools:
      #- icon: twitter
        #href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/swhawes/abcd-biostats-longitudinal
            #url:  "./tutorials.qmd"
          - text: Report a Bug
            url: https://github.com/swhawes/abcd-biostats-longitudinal/issues

  sidebar:
    - title: "Manuscript"
      logo: "./figures/lights.png"
      pinned: true
      tools:
        #- icon: twitter
         # href: https://twitter.com
        - icon: github
          menu:
            - text: Source Code
              url: https://github.com/swhawes/abcd-biostats-longitudinal
            - text: Report a Bug
              url: https://github.com/swhawes/test/abcd-biostats-longitudinal
      style: "docked"
      search: true
      background: light
      collapse-level: 1
      contents:
        - manuscript.qmd
    - title: "Tutorials"
      contents:
        - tutorials.qmd
        - section: "Traditional Linear Models"
          contents:
            - subfoldertest/1_Tutorials_DifferenceScores.qmd
            - 2_Tutorials_ResidualizedChangeScores.qmd
            - 3_Tutorials_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - 4_Tutorials_SignedRankTest.qmd
            - 5_Tutorials_MarginalModels.qmd
            - 6_Tutorials_GeneralizedEstimatingEquations.qmd
            - 7_Tutorials_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - 8_Tutorials_AutoregressiveCrosslaggedPanelModels.qmd
            - 9_Tutorials_LatentChangeScoresModels.qmd
            - 10_Tutorials_LatentGrowthCurveModels.qmd
            - 11_Tutorials_MultivariateLatentGrowthCurveModels.qmd
            - 12_Tutorials_LatentTransitionAnalysis.qmd
            - 13_Tutorials_GrowthMixtureModels.qmd
            - 14_Tutorials_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Tutorials_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Tutorials_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
    - title: "Examples"
      contents:
        - examples.qmd
        - section: "Traditional Linear Models"
          contents:
            - section: "Difference Scores"
              contents:
                - 1a_Examples_DifferenceScores_PairedTtests.qmd
                - 1b_Examples_DifferenceScores_SimpleRegression.qmd
            - section: "Residualized Change Scores"
              contents:
                - 2_Examples_ResidualizedChangeScores.qmd
            - section: "Linear Mixed Models"
              contents:
                - 3a_Examples_LinearMixedModels.qmd
                - 3b_Examples_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - section: "Signed-Rank Test"
              contents:
                - 4_Examples_SignedRankTest.qmd
            - section: "Marginal Models"
              contents:
                - 5_Examples_MarginalModels.qmd
            - section: "Generalized Estimating Equations"
              contents:
                - 6_Examples_GeneralizedEstimatingEquations.qmd
            - section: "Generalized Linear Mixed-Effects Models"
              contents:
                - 7_Examples_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - section: "Autoregressive Crosslagged Panel Models"
              contents:
                - 8_Examples_AutoregressiveCrosslaggedPanelModels.qmd
            - section: "Latent Change Scores Models"
              contents:
                - 9_Examples_LatentChangeScoresModels.qmd
            - section: "LatentGrowthCurveModels"
              contents:
                - 10_Examples_LatentGrowthCurveModels.qmd
            - section: "Multivariate Latent Growth Curve Models"
              contents:
                - 11_Examples_MultivariateLatentGrowthCurveModels.qmd
            - section: "Latent Transition Analysis"
              contents:
                - 12_Examples_LatentTransitionAnalysis.qmd
            - section: "Growth Mixture Models"
              contents:
                - 13_Examples_GrowthMixtureModels.qmd
            - section: "State-Trait Models"
              contents:
                - 14_Examples_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Examples_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Examples_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
        # navigation items
    - title: "Explanations"
      contents:
        - explanations.qmd
        - section: "Traditional Linear Models"
          contents:
            - 1_Explanations_DifferenceScores.qmd
            - 2_Explanations_ResidualizedChangeScores.qmd
            - 3_Explanations_LinearMixedModels.qmd
        - section: "Traditional Non-linear Models"
          contents:
            - 4_Explanations_SignedRankTest.qmd
            - 5_Explanations_MarginalModels.qmd
            - 6_Explanations_GeneralizedEstimatingEquations.qmd
            - 7_Explanations_GeneralizedLinearMixedEffectsModels.qmd
        - section: "SEM Approaches"
          contents:
            - 8_Explanations_AutoregressiveCrosslaggedPanelModels.qmd
            - 9_Explanations_LatentChangeScoresModels.qmd
            - 10_Explanations_LatentGrowthCurveModels.qmd
            - 11_Explanations_MultivariateLatentGrowthCurveModels.qmd
            - 12_Explanations_LatentTransitionAnalysis.qmd
            - 13_Explanations_GrowthMixtureModels.qmd
            - 14_Explanations_StateTraitModels.qmd
        - section: "Advanced SEM"
          contents:
            - 15_Explanations_RandomInterceptCrosslaggedPanelModels.qmd
            - 16_Explanations_LatentCurveModelsStructuredResiduals.qmd
        - section: "Longitudinal Neuroimaging"
          contents:
            - blank.qmd
        - section: "Twin Modeling & Genetics Designs"
          contents:
            - blank.qmd
        - section: "Data Wrangling"
          contents:
            - blank.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        - section: "List of Reference Material"
          contents:
            - ListofReferences.qmd

    - title: "Documentation"
      contents:
        - documentation.qmd

  page-footer:
    center:
      - text: "Longitudinal Analysis"
        href: reference.qmd
format:
  html:
    theme: styles.scss
    #theme:
      #light: cosmos #flatly
      #dark: darkly
    css: styles.css
    toc: true
    toc-depth: 1
    toc-expand: 3
    toc-title: Table of Contents
    anchor-sections: true
    smooth-scroll: true
    #fontsize: 1.1em
    linestretch: 1.5
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-fold: true
    code-summary: "Code"
    code-overflow: scroll
    code-line-numbers: TRUE
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    html-math-method: katex
    df-print: paged
    options: max.print=75000
    grid:
      sidebar-width: 425px

execute:
  echo: true
  message: false
  warning: false
  error: false
  #comment: NA
  cache: true
  cold-folding: true
  R.options: list(width=220)
  fig.align: "center"
  out.width: "75%"
  fig.asp: .75
  dev: "cairo_pdf"
  freeze: auto # re-render only when source changes

bibliography: references.bib

comments:
  hypothesis: true
