{
  "hash": "9f3c250825280a00169ad8fcd71feb96",
  "result": {
    "markdown": "---\ntitle: Difference Scores\nauthor: \"Biostatistics Working Group\"\n---\n\n\n## Overview\nDifference scores offer a straightforward statistical approach to compare data collected from the same individual across two measurement occasions. The difference between scores at two time points is taken as a measure of change. It is common to then perform statistical tests on the difference scores, such as being included as an outcome in a GLM analysis to test for differences in patterns of change over time and between groups. For example, difference scores may be used in a paired-samples t-test to compare mean test scores of students before and after attending a math workshop, or in a simple regression analysis to assess the effectiveness of a weight loss program by calculating the difference in weight between between groups of interest, before and after the program. This tutorial will guide you through computing and interpreting difference scores using R.\n\n![Figure x. Difference score add explanation or tag](./figures/Difference Score 1_Tutorial.png)\n\n### When to use Difference Score Models?\nYou should use difference scores in the following scenario:\n\n1. You want to know: The impact of interventions or time on a measured variable.\n2. Your variable: Has paired measurements, like pre-test and post-test scores.\n3. You have: Matched data for each set, ensuring valid difference computations.\n\n### Getting Started with Difference Score Models\nIn this tutorial, we will guide you through two simple examples of using difference scores. By the end of this tutorial, you will be able to:\n\n1. Understand the basic concepts of difference scores.\n2. Calculate difference scores using example data.\n3. Interpret the results of a difference scores analysis.\n\n## Basic Example\nIn this tutorial, we will begin by generating a sample dataset directly within R to ensure everyone has the same starting point and can follow along without needing to download or access external files. This generated dataset will serve as our example throughout this tutorial. In your own analyses, you'll likely start by importing your own data.\n\nThe simulated dataset created for this example consists of scores on a single outcome variable (\"Job_Satisfaction\") for 500 individuals each measured at two time points: T1-T2. \n\n#### Create Example Dataset\n\n::: {.cell hash='1_Tutorials_DifferenceScores_cache/html/unnamed-chunk-1_a7a3a29425e5c76fcebbe3f34c54b341'}\n\n```{.r .cell-code}\n# This will create a dataset with 1000 rows (2 rows for each of the 500 individuals).\n\n# Creating the example dataset\nset.seed(123) # for reproducibility\n\n# Setting the number of individuals for our sample data\nn <- 500\n\n# Specifying the desired correlation matrix for our data\ncor_matrix <- matrix(c(1, 0.30, \n                      0.30, 1), \n                      nrow=2)\n\n# Using Cholesky decomposition to generate correlated data\ncholesky <- chol(cor_matrix)\n\n# Generating correlated random data\nrandom_data <- matrix(rnorm(n * 2), ncol=2)\ncorrelated_data <- random_data %*% cholesky\n\n# Converting the generated data into a structured data frame\ndata <- data.frame(\n  Individual = rep(1:n, each=2),\n  TimePoint = rep(c(\"T1\", \"T2\"), times=n),\n  Job_Satisfaction = c(correlated_data[,1], correlated_data[,2])\n)\n```\n:::\n\n\n### View Dataset\n\n::: {.cell hash='1_Tutorials_DifferenceScores_cache/html/unnamed-chunk-2_df42c760970b92f18ca7883a39f8d4da'}\n\n```{.r .cell-code}\nhead(data)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Individual\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"TimePoint\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Job_Satisfaction\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"T1\",\"3\":\"-0.56047565\",\"_rn_\":\"1\"},{\"1\":\"1\",\"2\":\"T2\",\"3\":\"-0.23017749\",\"_rn_\":\"2\"},{\"1\":\"2\",\"2\":\"T1\",\"3\":\"1.55870831\",\"_rn_\":\"3\"},{\"1\":\"2\",\"2\":\"T2\",\"3\":\"0.07050839\",\"_rn_\":\"4\"},{\"1\":\"3\",\"2\":\"T1\",\"3\":\"0.12928774\",\"_rn_\":\"5\"},{\"1\":\"3\",\"2\":\"T2\",\"3\":\"1.71506499\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n### Model Specification and Estimation\nTo specify a Difference Score, we will quantify the change in a variable by subtracting its initial value from subsequent measurements. This approach captures the absolute change in the variable over time.\n\n#### Model\n\n::: {.cell hash='1_Tutorials_DifferenceScores_cache/html/unnamed-chunk-3_94c6492ed57a551ab981620c0a2d900f'}\n\n```{.r .cell-code}\n# Performing the paired t-test to compare Life Satisfaction scores at two time points\n# Extracting Job_Satisfaction scores for the two time points\nt1_scores <- data$Job_Satisfaction[data$TimePoint == \"T1\"]\nt2_scores <- data$Job_Satisfaction[data$TimePoint == \"T2\"]\n```\n:::\n\n\n#### Fit Model\n\n::: {.cell hash='1_Tutorials_DifferenceScores_cache/html/unnamed-chunk-4_3bc1f5166556f5b8b04b1014bb352470'}\n\n```{.r .cell-code}\nmodel <- t.test(t1_scores, t2_scores, mu = 0, paired = TRUE)\n```\n:::\n\n\n#### Model Summary\n\n::: {.cell hash='1_Tutorials_DifferenceScores_cache/html/unnamed-chunk-5_d8046b8dbab0b76682dfeee349bfc839'}\n\n```{.r .cell-code}\nprint(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  t1_scores and t2_scores\nt = 2.2206, df = 499, p-value = 0.02682\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.01659222 0.27137979\nsample estimates:\nmean difference \n       0.143986 \n```\n:::\n:::\n\n\n### Interpreting the Results\nThe paired t-test was conducted to compare Job Satisfaction scores at two time points: T1 and T2. The test yielded a t-value of t=2.221 with 499 degrees of freedom. The associated p-value is p=0.027. This p-value is greater than the common significance level of 0.05, which means that we do not have enough evidence to reject the null hypothesis. The 95% confidence interval for the mean difference ranges from 0.017 to 0.271. The observed mean difference between the two time points is 0.144.\n\n## Conclusion\nThere is no statistically significant difference in Job Satisfaction scores between the two time points, T1 and T2, based on the paired t-test results. The mean difference, although positive (0.144), is not significant at the 0.05 level.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}