{
  "hash": "319acf2c8bd5f2a31880439c2d2c4411",
  "result": {
    "markdown": "---\ntitle: \"Residualized Change Scores\"\nauthor: \"Biostatistics Working Group\"\n---\n\n\n# Mulitple Regression {.unnumbered}\n\n## Overview\n\n<p>\n\nThis example assesses whether height, measured at the 1-Year follow-up (T1) in a subsample of ABCD participants, is predicted by weight and height measured at baseline (T0). A visual inspection is further conducted via a scatterplot to graphically represent the relationship between height at Year_1 and weight at baseline, controlling for height at baseline. The ensuing analysis and interpretations are detailed in the subsequent sections.\n\n</p>\n\n## Preliminary Setup\n\n::: panel-tabset\n### Install Packages {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n> **This code installs the r packages necessary for this example, if\n> they are not already installed**\n\n\n::: {.cell messages='false' hash='2_HowTos_ResidualizedChangeScores_cache/html/pckg-install_6516d9aca71a3069ea1b6e99b1fbbd0b'}\n\n```{.r .cell-code}\n# Create a list of required packages\npackages_required <- c(\"tidyverse\",\"rstatix\",\"DT\",\"lme4\")\n\n# Check which packages are not installed and install them\npackages_to_install <- setdiff(packages_required, rownames(installed.packages()))\nif (length(packages_to_install) > 0) {\n    install.packages(packages_to_install)\n}\n\n# Load the required packages\nlapply(packages_required, library, character.only = TRUE)\n```\n:::\n\n:::\n\n### Load Packages\n\n::: blue\n**This code loads the r libraries necessary for this example**\n\n\n::: {.cell messages='false' hash='2_HowTos_ResidualizedChangeScores_cache/html/lib-load_e6462003136df54fe5d07efd76cda61c'}\n\n```{.r .cell-code}\nlibrary(tidyverse)    # Collection of R packages for data science\nlibrary(rstatix)      # Pipe-friendly framework for basic statistical tests\nlibrary(DT)           # Rendering interactive data tables\nlibrary(lme4)         # Linear mixed-effects models\n```\n:::\n\n:::\n\n### Config Options\n\n::: blue\n**This code configures knitr code chunk options**\n\n\n::: {.cell messages='false' hash='2_HowTos_ResidualizedChangeScores_cache/html/config_f487561b92135e15587d3582f9207f9a'}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = T, message=F, warning=F, error=F, \n                      comment=NA, cache=T, code_folding=T,\n                      R.options=list(width=220, digits = 3),\n                      fig.align='center', \n                      out.width='75%', fig.asp=.75)\n```\n:::\n\n:::\n:::\n\n## Descriptives Overview\n\n::: panel-tabset\n### Read and View Data {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n**This code reads in and shows the data to be used in the current\nexample**\n\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code}\n# Set the data paths\ndata_path_1 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/demo5.0.rds\"\ndata_path_2 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/core-rds-5.0/non-imaging_excluding_nt_5.0.rds\"\n\n# Read the data\ndata_demographics <- readRDS(data_path_1)\ndata_nonimaging <- readRDS(data_path_2)\n\n# Subset the nonimaging data to include desired variables\nselected_vars <- c(\"src_subject_id\", \"eventname\", \"nihtbx_totalcomp_fc\", \"anthroweightcalc\", \"anthroheightcalc\")\nsubset_data <- data_nonimaging[, selected_vars]\n\nlibrary(dplyr)\n# # Merge the datasets on 'src_subject_id' and 'eventname'\nmerged_data <- data_demographics %>%\n  full_join(subset_data, by = c(\"src_subject_id\", \"eventname\"))\n\n# Inspect the merged data structure\nstr(merged_data)\n\n# Define event names to be retained in the analysis and convert variables to appropriate data types\neventnames_to_include <- c(\"baseline_year_1_arm_1\",\n                           \"1_year_follow_up_y_arm_1\",\n                           \"2_year_follow_up_y_arm_1\",\n                           \"3_year_follow_up_y_arm_1\",\n                           \"4_year_follow_up_y_arm_1\")\n\ndf <- merged_data %>%\n  filter(eventname %in% eventnames_to_include) %>%\n  mutate(\n    src_subject_id = as.factor(src_subject_id),\n    eventname = factor(eventname, levels = eventnames_to_include, ordered = TRUE),\n    age = as.numeric(age),\n    sex = as.factor(sex),\n    race.4level = as.factor(race.4level),\n    hisp = as.factor(hisp),\n    high.educ.bl = as.factor(high.educ.bl),\n    household.income.bl = as.factor(household.income.bl),\n    acs_raked_propensity_score = as.numeric(acs_raked_propensity_score),\n    rel_family_id.bl = as.factor(rel_family_id.bl),\n    site_id_l = as.factor(site_id_l),\n    nihtbx_totalcomp_fc = as.numeric(nihtbx_totalcomp_fc),\n    anthroweightcalc = as.numeric(anthroweightcalc),\n    anthroheightcalc = as.numeric(anthroheightcalc)\n  ) %>%\n  # Exclude cases from unused assessment waves\n  filter(!is.na(eventname))\n```\n:::\n\n:::\n\n### Descriptives\n\n::: blue\n**This code creates a descriptives table**\n\n\n::: {.cell layout-align=\"center\" messages='false' hash='2_HowTos_ResidualizedChangeScores_cache/html/descriptives_1ff77283dddd096d4b62cbc3565ca559'}\n\n```{.r .cell-code}\n# Define a function to compute descriptives\ncompute_descriptives <- function(data, event_name) {\n  # For factor variables\n  sex_desc <- paste0(table(data$sex), \" (\", round(100 * prop.table(table(data$sex)), 1), \"%)\")\n  race_desc <- paste0(table(data$race.4level), \" (\", round(100 * prop.table(table(data$race.4level)), 1), \"%)\")\n  \n  # For numeric variables\n  age_desc <- paste0(round(mean(data$age, na.rm = TRUE), 2), \" (\", round(sd(data$age, na.rm = TRUE), 2), \")\")\n  weight_desc <- paste0(round(mean(data$anthroweightcalc, na.rm = TRUE), 2), \" (\", round(sd(data$anthroweightcalc, na.rm = TRUE), 2), \")\")\n  height_desc <- paste0(round(mean(data$anthroheightcalc, na.rm = TRUE), 2), \" (\", round(sd(data$anthroheightcalc, na.rm = TRUE), 2), \")\")\n  \n  # Combine into a data frame\n  desc_df <- data.frame(\n    Variable = c(\"Sex - Female\", \"Sex - Male or other\", \"Race - Asian\", \"Race - Black\", \"Race - Other/Mixed\", \"Race - White\", \"Age\", \"Weight\", \"Height\"),\n    Value = c(sex_desc, race_desc, age_desc, weight_desc, height_desc)\n  )\n  \n  # Rename the Value column based on event name\n  colnames(desc_df)[2] <- event_name\n  return(desc_df)\n}\n\n# Compute descriptives for each event\nbaseline_desc <- compute_descriptives(subset(df, eventname == \"baseline_year_1_arm_1\"), \"baseline_year_1_arm_1\")\none_year_desc <- compute_descriptives(subset(df, eventname == \"1_year_follow_up_y_arm_1\"), \"1_year_follow_up_y_arm_1\")\ntwo_year_desc <- compute_descriptives(subset(df, eventname == \"2_year_follow_up_y_arm_1\"), \"2_year_follow_up_y_arm_1\")\nthree_year_desc <- compute_descriptives(subset(df, eventname == \"3_year_follow_up_y_arm_1\"), \"3_year_follow_up_y_arm_1\")\n\n# Join all data frames side-by-side\nfinal_table <- baseline_desc %>%\n  left_join(one_year_desc, by = \"Variable\") %>%\n  left_join(two_year_desc, by = \"Variable\") %>%\n  left_join(three_year_desc, by = \"Variable\")\n\n# Adjust for the required format\nfinal_table[1:6, 3:5] <- NA\n\n# Round numeric values to two decimal places\nnumeric_cols <- sapply(final_table, is.numeric)\nfinal_table[numeric_cols] <- lapply(final_table[numeric_cols], round, 2)\n\n# Create heading rows with the same columns as final_table\nheading_rows <- data.frame(\n  Variable = c(\"Sex\", \"Race\"),\n  baseline_year_1_arm_1 = NA_real_,\n  `1_year_follow_up_y_arm_1` = NA_real_,\n  `2_year_follow_up_y_arm_1` = NA_real_,\n  `3_year_follow_up_y_arm_1` = NA_real_\n)\n\n# Set column names of heading_rows to match final_table\ncolnames(heading_rows) <- colnames(final_table)\n\n# Introduce group labels and adjust the \"Variable\" column\nfinal_table <- rbind(\n                    heading_rows[1,], \n                    final_table[1:2,],\n                    heading_rows[2,], \n                    final_table[3:6,], \n                    final_table[7:9,]\n                    )\n\n# Update the Variable column to remove redundant factor variable name\nfinal_table$Variable <- gsub(\"Sex - \", \"\", final_table$Variable)\nfinal_table$Variable <- gsub(\"Race - \", \"\", final_table$Variable)\nfinal_table$Variable[final_table$Variable == \"Male or other\"] <- \"Male\"\n\n# Add non-breaking spaces for increased indentation\nfinal_table$Variable[final_table$Variable %in% c(\"Female\", \"Male\", \"Asian\", \"Black\", \"Other/Mixed\", \"White\")] <- \n  paste0(rep(\"&nbsp;\", 6), final_table$Variable[final_table$Variable %in% c(\"Female\", \"Male\", \"Asian\", \"Black\", \"Other/Mixed\", \"White\")])\n\n# Update column headers\ncolnames(final_table)[2:5] <- c(\"Baseline\", \"Year 1\", \"Year 2\", \"Year 3\")\n\n# Display the table interactively without row names, with updated column headers, and with HTML entities rendered\ndatatable(final_table, \n          colnames = c(\"\", \"Baseline\", \"Year 1\", \"Year 2\", \"Year 3\"),\n          options = list(pageLength = nrow(final_table), autoWidth = TRUE),\n          rownames = FALSE, escape = FALSE,\n          caption = \"Descriptives Table\")  # Add table title\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"datatables html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-9aea4eef93c22c72164a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-9aea4eef93c22c72164a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Descriptives Table<\\/caption>\",\"data\":[[\"Sex\",\"&nbsp;Female\",\"&nbsp;Male\",\"Race\",\"&nbsp;Asian\",\"&nbsp;Black\",\"&nbsp;Other/Mixed\",\"&nbsp;White\",\"Age\",\"Weight\",\"Height\"],[null,\"5677 (47.8%)\",\"6191 (52.2%)\",null,\"52 (0.5%)\",\"1869 (16.4%)\",\"1992 (17.4%)\",\"7517 (65.8%)\",\"9.48 (0.51)\",\"82.55 (23.76)\",\"55.24 (3.33)\"],[null,null,null,null,null,null,null,null,\"10.51 (1.81)\",\"94.27 (28.36)\",\"57.59 (3.65)\"],[null,null,null,null,null,null,null,null,\"11.6 (1.4)\",\"108.62 (48.86)\",\"60.25 (3.61)\"],[null,null,null,null,null,null,null,null,\"12.47 (0.77)\",\"123.4 (38.25)\",\"62.45 (4.1)\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th><\\/th>\\n      <th>Baseline<\\/th>\\n      <th>Year 1<\\/th>\\n      <th>Year 2<\\/th>\\n      <th>Year 3<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":11,\"autoWidth\":true,\"columnDefs\":[],\"order\":[],\"orderClasses\":false,\"lengthMenu\":[10,11,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n:::\n:::\n\n## Results\n\n::: panel-tabset\n### Build Model {.tabset .tabset-fade .tabset-pills}\n\n::: blue\nThe code snippet below tells R to conduct a multiple regression analysis by subtracting each participant's height at T1 from their height at T0. Relevant summary statistics are also provided.\n\n**Compute Multiple Regression Model**\n\n::: {.cell layout-align=\"center\" hash='2_HowTos_ResidualizedChangeScores_cache/html/build-model-resid-regression-1_330985bc782f08239f5d844c0dc4214c'}\n\n```{.r .fold-hide .cell-code}\n# Split data using the correct eventname values\nbaseline_data <- df %>% \n  filter(eventname == \"baseline_year_1_arm_1\") %>% \n  select(src_subject_id, Height_baseline = anthroheightcalc, Weight_baseline = anthroweightcalc)\n\nfollowup_data <- df %>% \n  filter(eventname == \"1_year_follow_up_y_arm_1\") %>% \n  select(src_subject_id, Height_followup = anthroheightcalc)\n\n# Merge baseline and follow-up data\nmerged_data <- baseline_data %>%\n  left_join(followup_data, by = \"src_subject_id\")\n\n# Check the first few rows of the merged data\n#head(merged_data)\n\n# Fit the regression model excluding NA values\nmodel <- lm(Height_followup ~ Height_baseline + Weight_baseline, data = merged_data, na.action = na.exclude)\n```\n:::\n\n\n:::\n\n### Model Summary {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\nA plot to show xxxxx.\n\n::: {.cell layout-align=\"center\" hash='2_HowTos_ResidualizedChangeScores_cache/html/model-checking_bde8a3ee79f5e68bcbba79d84e9b8155'}\n\n```{.r .cell-code}\nmodel_summary <- summary(model)\nprint(model_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Height_followup ~ Height_baseline + Weight_baseline, \n    data = merged_data, na.action = na.exclude)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-53.49  -0.83  -0.09   0.74  65.88 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     17.18159    0.41712    41.2   <2e-16 ***\nHeight_baseline  0.68665    0.00847    81.0   <2e-16 ***\nWeight_baseline  0.03026    0.00120    25.3   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.38 on 11130 degrees of freedom\n  (735 observations deleted due to missingness)\nMultiple R-squared:  0.575,\tAdjusted R-squared:  0.575 \nF-statistic: 7.54e+03 on 2 and 11130 DF,  p-value: <2e-16\n```\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))  # Set up a 2x2 plotting area\nplot(model)  # Generate diagnostic plots\n```\n\n::: {.cell-output-display}\n![](2_HowTos_ResidualizedChangeScores_files/figure-html/model-checking-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThis regression analysis evaluates how baseline height and weight predict children's height at a 1-year follow-up. The output from our model provides several key statistics:\n\ni. an F-statistic of 7539.2168865;\nii. degrees of freedom of 11130;\niii. parameter estimates for baseline height and weight;\niv. standard errors for these estimates; and\nv. p-values for the significance of these estimates.\n\nFor every one unit increase in baseline height, there's an associated increase of approximately 0.687 units in the follow-up height, and this effect was statistically significant with a p-value of 0. Similarly, for every one unit increase in baseline weight, there's an associated increase of approximately 0.0303 units in the follow-up height, which is also statistically significant with a p-value of 3.9902186\\times 10^{-137}. Overall, this model explains a substantial portion of the variance in follow-up height, with an adjusted R-squared value of 0.5753. The overall model is highly significant with a p-value less than 0, indicating that the predictors, collectively, have a significant relationship with the dependent variable.\n\n:::\n\n### Model Plots  {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\n::: {.cell layout-align=\"center\" hash='2_HowTos_ResidualizedChangeScores_cache/html/scatterplot_2d9e2bfef4c37e6f1aa06e48634bd388'}\n\n```{.r .cell-code}\n# Scatterplot with regression line for Weight_baseline\nggplot(merged_data, aes(x = Weight_baseline, y = Height_followup)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", color = \"black\") + \n  labs(title = \"Relationship between Baseline Weight and Follow-up Height\",\n       x = \"Baseline Weight\",\n       y = \"Follow-up Height\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2_HowTos_ResidualizedChangeScores_files/figure-html/scatterplot-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThe scatterplot visually depicts the relationship between children's weights at baseline (Weight_baseline) and their heights at Year_1 (Height_followup). Each point on the plot represents a child, with their baseline weight plotted on the x-axis and their Year_1 height on the y-axis. The clear positive linear trend, as illustrated by the black regression line, indicates that children who had higher weights at baseline generally had higher heights at Year_1. While further statistical analyses can quantify the strength and direction of this relationship, visually, the data suggests a pronounced positive association between baseline weight and follow-up height.\n\n:::\n:::\n\n## Wrapping Up\n<div class = \"blue\">\n\n::: panel-tabset\n### Write-up {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\nThe regression analysis was conducted to predict children's height at the 1-Year follow-up using their baseline height (Height_baseline) and weight (Weight_baseline). Both predictors were statistically significant. Specifically, for every one-unit increase in baseline height, the height at Year_1 increased by approximately 0.687 units, while holding weight constant. Similarly, for every one-unit increase in baseline weight, the height at Year_1 increased by about 0.0303 units, while holding baseline height constant. The overall model explained a substantial 57.53% of the variance in height at the 1-Year follow-up, as indicated by the adjusted R-squared value.\n  \n\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.28/datatables.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/dt-core-1.13.4/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-1.13.4/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-1.13.4/js/jquery.dataTables.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}